### ISSUE TITLE
What does a negative exploitability mean?

### ISSUE THREAD

**Issue by aipoker39** [bupticybee/TexasSolver#176]
Thanks for the project, I ran the solver using the default configs in README, and it output the following:

```
...
Iter: 81
player 0 exploitability 6.5465393
player 1 exploitability -6.1164308
Total exploitability 0.43010855 precent
time used: 299.299
...
```

As you can see, the exploitability of player 1 is negative. What does that mean? Thanks in advance.

**Comment by bupticybee** [comment]
because in this case, the best exploitibility you can get is negetive, for player1, but for all player, it sums to be positive for sure.

**Comment by aipoker39** [comment]
What's the definition of exploitability? My understanding is that it indicates the distance between the strategy and nash equilibrium. How can the distance be a negative number?

**Comment by bupticybee** [comment]
> What's the definition of exploitability? My understanding is that it indicates the distance between the strategy and nash equilibrium. How can the distance be a negative number?

In the above log,

player 0 exploitability  means how much you can get from p0 if your strategy is optimal
player 1 exploitability  means how much you can get from p1 if your strategy is optimal

So it can be negative, because even if your strategy is optimal, you can still have a negative ev against a single player.

Since you can never know what a nash equilibrium is when running cfr , you can't calculate what you describe "the distance between stratgy and nash".

**Comment by aipoker39** [comment]
Thank you for the prompt and clear explanation; it has greatly helped my understanding. As I delve deeper into this repository and the codebase, having comprehensive documentation on the code and its underlying algorithms would be immensely beneficial. Regardless, I truly appreciate your efforts and contributions. Thanks again!

**Comment by bupticybee** [comment]
Thanks. Closing since the issue is resolved. Reopen if necessary.
