### ISSUE TITLE
Suggestion - Allow Specification of Hand

### ISSUE THREAD

**Issue by Jared-7** [bupticybee/TexasSolver#51]
Hey! Awesome solver you've put together and appreciate you making it open source. Not an issue but some suggestions to improve. 

To save time in some solving situations, it might be useful to allow the user to specify a specific hand one player has as well as their range. This could help in reducing the size of the tree needed to compute for some situations. 

Another suggestion could be to pre-program the actions of one player up to the turn/river in order to automatically narrow their range without having to calculate the full tree. 

Again, not entirely sure on the feasibility of these ideas, but would be appreciated!

**Comment by bupticybee** [comment]
Thank you for your suggestion, however some of them might be impretical, others are doable:

1.  " allow the user to specify a specific hand one player has as well as their range" this makes no sense in a cfr-like algorithm, cfr-like algorithms must consider each possible hand in range to ensure nash equilibrium is reached.
2. "pre-program the actions of one player up to the turn/river in order to automatically narrow their range " I think this is somehow very similar "Node Lock" in piosolver, This is actually a common issue and it has been mentioned many times in various discussion around this project. After I complete the main function of the solver, I will put these things to schedule.

**Comment by Jared-7** [comment]
Thanks for getting back to me and for the feedback - looking forward to what comes next in this project!
