### ISSUE TITLE
Enhancement Request: include board info and hand probability into output json

### ISSUE THREAD

**Issue by to2y** [bupticybee/TexasSolver#53]
Thank you for the great solver!

I'm developing the output viewer (but still alpha...) and I would like output json include below:

* board info
   output json does not have flop board card info, if it is added into the output json, viewer easily show board info from output json.

* hand survival probability (from pre-flop)
   You can specify open percentages of each hands, for example 99 is 75%, however, in output json's strategy of 99, sum of each action is 1.0 for 99. If you calc survived hand percentage from pre-flop, we have to remember input open probability and also remember parent node's call percentage and multiply them.
   It would be useful if hands info of strategy contains survived percentage independently from action percentage.
   like this:
      2s2d:
         [0]: 0.99..
         [1]: 0.0012..
         [2]: 0.0000...
         survived: 0.75

**Comment by bupticybee** [comment]
I see, here are my plans for these problems:
1. I will start to redesign a save format right after I finish the first GUI version, I will take your suggestion into account, as you probably already figure out, json is not suitable to save strategy in texas holdem.
2. It's the same concept to "range number after a series actions". It can be actually calculated given initial range for both player, and strategy after. I already implement this in my GUI version, saving this to file will take some extra disk space so I still have to consider if save range number to output file is a good idea. I might end up save only the initial range instead. 

My is that. because it will be some days before I finally solve these problems, there are ways to avoid them now:
1. format the json file name to include board info, e.g. a output file name like xx_4h8dJh.json
2. save initial range and strategy seperately,and when you need to show them, read them seperately, or include them in a big save file(maybe a zip file).


ps: I'm developing a GUI actually, now it looks like this:
<img width="1076" alt="截屏2021-11-01 下午2 47 41" src="https://user-images.githubusercontent.com/9393610/139633620-b48906d3-8387-40b8-9614-5ede3d864714.png">

**Comment by to2y** [comment]
thank you for your reply @bupticybee 

OK, I will wait your GUI version, and until that I'm developing a viewer of output json. (Considering survived percentage is very difficult though). If viewer becomes alpha, I will open it on github.

Your GUI look great, it would be possible to show the EVs for every hand!

**Comment by bupticybee** [comment]
> thank you for your reply @bupticybee
> 
> OK, I will wait your GUI version, and until that I'm developing a viewer of output json. (Considering survived percentage is very difficult though). If viewer becomes alpha, I will open it on github.
> 
> Your GUI look great, it would be possible to show the EVs for every hand!

Thank you very much for your effort, as I mentioned, my GUI version current don't have the ability to ready the json file generated by solver (ironically). Your viewer would be truely great news for me and this project. Looking forward to future cooperation!
