### ISSUE TITLE
On which paper do your algorithm based on?

### ISSUE THREAD

**Issue by RamboWu** [bupticybee/TexasSolver#82]
I tried to understand what optimization you did that differs from  normal cfr, but it's quite a work to read pure codes without any comments.
If you'd tell me which paper to researh, it would be much easier. 
Thx again for your hard work.

**Comment by bupticybee** [comment]
It's basically based on discount-cfr but I do a lot of optimization upon it. Some of them I think is quite original (especially those tricks that works) so some of the tricks you will find no paper to refer to.

However I think it's still possible to underestand most part of the code without any paper. You can always come back to the issue to ask why some code is written one way rather than other. Always welcome curious people like yourself.

**Comment by bupticybee** [comment]
Closing because this issue is considered solved.
